accounts/urls.py
from django.urls import path
from .views.profile_views import MyProfile, MyProfileUpdate
from .views.users_views import UsersList
from .views.sign_views import (
    LogInView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView
)


app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    #
    # path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    #
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),
    #
    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),
    #
    #
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    path('<int:pk>', MyProfile.as_view(), name='myprofile'),
    path('profileupdate/<int:pk>', MyProfileUpdate.as_view(), name='profileupdate'),
    # path('users/', AllUsersList.as_view(), name='users'),
    # path('create/', CreateUser.as_view(), name='create'),
    # path('delete/<int:pk>', DeleteUser.as_view(), name='delete'),
    # path('detail/<int:pk>', DetailUser.as_view(), name='detail'),
    # path('update/<int:pk>', UserUpdate.as_view(), name='update'),
    # path('mygrouplist/', MyGroupList.as_view(), name='mygrouplist'),
    path('users/', UsersList.as_view(), name='users'),
]

api/urls.py
from api.views.accounts import AccountViewSet
from api.views.invites import InviteViewSet, InviteRegistrationViewSet
from api.views.projects import ProjectViewSet
from api.views.donations import DonationViewSet

from rest_framework.routers import DefaultRouter
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views.accounts import account_registration_handler
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="API for project GrandCore",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register('user', AccountViewSet)
router.register('invite', InviteViewSet)
router.register('invite_reg', InviteRegistrationViewSet)
router.register('project', ProjectViewSet)
router.register('donation', DonationViewSet)

jwturlpatterns = [
    path('/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('register_user', account_registration_handler),
] + router.urls  + jwturlpatterns

backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import about_page, home_page
from accounts.views.users_views import UsersList

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("accounts/", include("accounts.urls")),
    path("about/", about_page, name="about"),
    path("", home_page, name="home"),
    path("projects/", include("projects.urls")),
    path("community/", UsersList.as_view(), name="community"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

accounts/views/profile_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, FormView, DetailView, ListView, UpdateView, CreateView, DeleteView
from ..models import Account, Activation
from ..forms import ProfileForm, CreateForm
from django.urls import reverse_lazy
from projects.models import Project
from donations.models import Donation


class MyProfile(LoginRequiredMixin, DetailView):
    model = Account
    context_object_name = 'user'
    template_name = 'accounts/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('accounts:myprofile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_instance = Account.objects.get(pk=self.get_object().pk)

        user_founded_projects = Project.objects.filter(author=user_instance)

        projects_ids = user_founded_projects.values_list('pk', flat=True)
        user_supported_projects = Donation.objects.filter(user=user_instance, for_project__in=list(projects_ids))

        context['user_founded_projects'] = user_founded_projects

        context['user_supported_projects'] = user_supported_projects

        return context

    def get_success_url(self):
        return reverse_lazy('accounts:myprofile', kwargs={'pk': self.object.pk})


class MyProfileUpdate(LoginRequiredMixin, UpdateView):
    model = Account
    template_name = 'accounts/profileupdate.html'
    form_class = ProfileForm
    success_url = reverse_lazy('accounts:profileupdate')

    def get_success_url(self):
        return reverse_lazy('accounts:profileupdate', kwargs={'pk': self.object.pk})

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #
    #     user_orders = Order.objects.filter(client=self.object.pk).order_by('-created')
    #     context['user_orders'] = user_orders
    #
    #     print(context)
    #     return context

    # def form_valid(self, request, form):
    #     user = request.user
    #
    #     if request.method == "POST":
    #         form = ProfileForm(request.POST)
    #         if form.is_valid():
    #             obj = form.save(commit=False)
    #             obj.user = request.user
    #             obj.save()
    #             # Without this next line the tags won't be saved.
    #             form.save_m2m()

accounts/views/sign_views.py
from django.contrib.auth import login, authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth import login as auth_logout
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LogoutView as BaseLogoutView, PasswordChangeView as BasePasswordChangeView,
    PasswordResetDoneView as BasePasswordResetDoneView, PasswordResetConfirmView as BasePasswordResetConfirmView,
)
from django.shortcuts import redirect
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _

from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView
from django.conf import settings

from django.shortcuts import get_object_or_404
from django.contrib import messages

from ..utils import (
    send_activation_email, send_reset_password_email, send_activation_change_email,
)
from ..forms import (
    SignInViaEmailForm, SignUpForm,
    RestorePasswordForm, RestorePasswordViaEmailOrUsernameForm,
    ResendActivationCodeForm, ResendActivationCodeViaEmailForm, ChangeProfileForm, ChangeEmailForm,
)
from ..models import Activation
from invite.models import InviteRegistration
from api.views.accounts import create_invite_registration, check_invite_not_empty, is_check_invite_exists


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        # Redirect to the index page if the user already authenticated
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)

        return super().dispatch(request, *args, **kwargs)


class LogInView(GuestOnlyView, FormView):
    template_name = 'accounts/login.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.LOGIN_VIA_EMAIL:
            return SignInViaEmailForm

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request = self.request

        # If the test cookie worked, go ahead and delete it since its no longer needed
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        # The default Django's "remember me" lifetime is 2 weeks and can be changed by modifying
        # the SESSION_COOKIE_AGE settings' option.
        if settings.USE_REMEMBER_ME:
            if not form.cleaned_data['remember_me']:
                request.session.set_expiry(0)

        login(request, form.user_cache)

        redirect_to = request.POST.get(REDIRECT_FIELD_NAME, request.GET.get(REDIRECT_FIELD_NAME))
        url_is_safe = is_safe_url(redirect_to, allowed_hosts=request.get_host(), require_https=request.is_secure())

        if url_is_safe:
            return redirect(redirect_to)

        return redirect(settings.LOGIN_REDIRECT_URL)


class SignUpView(FormView):
    template_name = 'accounts/signin.html'
    form_class = SignUpForm

    def form_valid(self, form):
        request = self.request
        user = form.save(commit=False)

        if settings.DISABLE_USERNAME:
            # Set a temporary username
            user.username = get_random_string()
        else:
            user.username = form.cleaned_data['email']

        # if settings.ENABLE_USER_ACTIVATION:
        user.is_active = False

        invite = request.POST['invite']

        if is_check_invite_exists(invite):
            if check_invite_not_empty(invite):

                # Create a user record
                user.save()
                create_invite_registration(invite, user)

                if settings.ENABLE_USER_ACTIVATION:
                    code = get_random_string(20)

                    act = Activation()
                    act.code = code
                    act.user = user
                    act.save()

                    send_activation_email(request, user.email, code)

                    messages.success(
                        request, _('You are signed up. To activate the account, follow the link sent to the mail.'))
                else:
                    raw_password = form.cleaned_data['password']

                    user = authenticate(username=user.username, password=raw_password)
                    login(request, user)

                    messages.success(request, _('You are successfully signed up!'))

                    # Change the username to the "user_ID" form
                    if settings.DISABLE_USERNAME:
                        user.username = f'user_{user.id}'
                        user.save()

                    return redirect('accounts/login')
            else:
                messages.success(
                    request, _('Invite empty.'))

        else:
            messages.success(
                request, _('This invite dose note exists.'))

        return redirect('/')


class ActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(Activation, code=code)

        # Activate profile
        user = act.user
        user.is_active = True
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully activated your account!'))

        return redirect('accounts:login')


class ResendActivationCodeView(GuestOnlyView, FormView):
    template_name = 'accounts/resend_activation_code.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.DISABLE_USERNAME:
            return ResendActivationCodeViaEmailForm

        return ResendActivationCodeForm

    def form_valid(self, form):
        user = form.user_cache

        activation = user.activation_set.first()
        activation.delete()

        code = get_random_string(20)

        act = InviteRegistration()
        # act.code = code
        # act.user = user
        act.save()

        send_activation_email(self.request, user.email, code)

        messages.success(self.request, _('A new activation code has been sent to your email address.'))

        return redirect('accounts:resend_activation_code')


class RestorePasswordView(GuestOnlyView, FormView):
    template_name = 'accounts/restore_password.html'

    @staticmethod
    def get_form_class(**kwargs):
        if settings.RESTORE_PASSWORD_VIA_EMAIL_OR_USERNAME:
            return RestorePasswordViaEmailOrUsernameForm

        return RestorePasswordForm

    def form_valid(self, form):
        user = form.user_cache
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk)).decode()

        send_reset_password_email(self.request, user.email, token, uid)

        return redirect('accounts:restore_password_done')


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_profile.html'
    form_class = ChangeProfileForm

    def get_initial(self):
        user = self.request.user
        initial = super().get_initial()
        initial['first_name'] = user.first_name
        initial['last_name'] = user.last_name
        return initial

    def form_valid(self, form):
        user = self.request.user
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.save()

        messages.success(self.request, _('Profile data has been successfully updated.'))

        return redirect('accounts:change_profile')


class ChangeEmailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/profile/change_email.html'
    form_class = ChangeEmailForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial

    def form_valid(self, form):
        user = self.request.user
        email = form.cleaned_data['email']

        if settings.ENABLE_ACTIVATION_AFTER_EMAIL_CHANGE:
            code = get_random_string(20)

            act = InviteRegistration()
            # act.code = code
            # act.user = user
            # act.email = email
            act.save()

            send_activation_change_email(self.request, email, code)

            messages.success(self.request, _('To complete the change of email address, click on the link sent to it.'))
        else:
            user.email = email
            user.save()

            messages.success(self.request, _('Email successfully changed.'))

        return redirect('accounts:change_email')


class ChangeEmailActivateView(View):
    @staticmethod
    def get(request, code):
        act = get_object_or_404(InviteRegistration, code=code)

        # Change the email
        user = act.user
        user.email = act.email
        user.save()

        # Remove the activation record
        act.delete()

        messages.success(request, _('You have successfully changed your email!'))

        return redirect('accounts:change_email')


class ChangePasswordView(BasePasswordChangeView):
    template_name = 'accounts/profile/change_password.html'

    def form_valid(self, form):
        # Change the password
        user = form.save()

        # Re-authentication
        login(self.request, user)

accounts/views/users_views.py
from django.views.generic import ListView
from accounts.models import Account


class UsersList(ListView):
    queryset = Account.objects.filter(is_active=True)
    template_name = 'accounts/users_list.html'
    context_object_name = 'users'
    paginate_by = 2

accounts/templates/accounts/login.html
{% extends 'index.html' %}

{% load static %}
{% load bootstrap4 %}


{% block page_title %}
Login
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block content %}

<div class="page-login page-auth">
    <div class="page-auth__content">
        <div class="page-auth-selector">
      <span class="page-auth-selector__item active">
        Вход
      </span>

            <a href="{% url 'accounts:sign_up' %}" class="page-auth-selector__item">
                Регистрация
            </a>
        </div>

        <form method="POST" class="page-auth__auth-form">
            {% csrf_token %}
            <div class="input-field">
                <input class="input input--height" type="text" name="email" required>
                <label class="input__label">Email</label>
                <span class="input__error"></span>
            </div>

            <div class="input-field">
                <input class="input input--height" type="password" name="password" required>
                <label class="input__label">Пароль</label>
                <span class="input__error"></span>
            </div>

            <a href="auth-login-passreset.html" class="input__sub">Забыли пароль?</a>

            <input type="submit" class="btn btn--green btn--big btn--width" value="Войти">

            <div class="page-auth__error">
                <!-- Неправельный логин или пароль -->
            </div>
        </form>
    </div>
</div>

<!--    <a href="{#% url 'accounts:restore_password' %#}">I forgot my password</a><br>--

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'index.html' %}

{% load static %}


{% block page_title %}
{{ user.email }}
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static '/accounts/css/style_accounts.css' %}">
{% endblock %}

{% block content %}
{% if request.user.pk == user.pk or request.user.is_superuser %}
<div class="page-user">
  <div class="page-user-container">
    <!-- profile block -->
    <div class="page-user-profile page-user-profile_bottom">
      <!-- photo -->
      <div class="page-user-profile__img">
          <img class="page-user-profile__img" src="/media/{% firstof user.avatar 'user-placeholder.svg' %}" alt="User profile picture">
      </div>
      <!-- info -->
      <div class="page-user-profile__user-wrap">
        <!-- skills and name -->
        <h2 class="page-user-profile__title">
            {{ user.first_name|default:'John' }}
        </h2>
        <p class="page-user-profile__skills">
                {% for skill in user.skills.all %}
                {{ skill }}
                {% endfor %}
        </p>
        <!-- status -->
        <div class="page-user-status">
          <a href="#" class="page-user-status__rank page-user-status_bottom">
            <img src="{% static '/img/page-user/icon.png' %}" alt="" class="page-user-status__rank-icon">
            {{ user.occupation|default:'' }}
          </a>
          <p class="page-user-status__rating page-user-status_bottom">
            Рейтинг:
          </p>
        </div>
        <!-- btn -->
        <div class="page-user-btn">
          <a href="{% url 'accounts:profileupdate' pk=user.pk %}" class="page-user-btn__edit">
            Edit Profile
          </a>
          <a href="tg://resolve?domain={{ user.telegram|default:'' }}" class="page-user-btn__message">
            <img src="{% static '/img/page-user/telegram.svg' %}" alt="" class="page-user-btn__message_telegram">
            Send a message
          </a>
        </div>
      </div>
    </div>
    <!-- Projects  -->
    <div class="page-user-projects ">
      <!-- menu -->
      <ul class="page-user-projects-menu">
        <!-- Projects Founded -->
        <li class="page-user-projects-menu__item">
          <a href="#" class="page-user-projects-menu__link page-user-projects-menu__link_active">
            Projects Founded {{user.projects.count|default:'0'}}
          </a>
        </li>
        <!-- Projects Supported -->
        <li class="page-user-projects-menu__item">
          <a href="#" class="page-user-projects-menu__link">
            Projects Supported {{user.donations.count|default:'0'}}
          </a>
        </li>
        <!-- Projects Liked -->
        <li class="page-user-projects-menu__item">
          <a href="#" class="page-user-projects-menu__link">
            Projects Liked 608
          </a>
        </li>
      </ul>
      <!-- projects cards -->
      <div class="page-user-cards">
        {% for project in user_founded_projects %}
          {% include 'accounts/components/project_block.html' with proj=project %}
        {% endfor %}
        <!-- card -->
        <article class="page-user-card">
          <img src="{% static '/img/page-user/page-user-bg1.jpg' %}" alt="" class="page-user-card__img">
          <div class="page-user-card__content-wrap">
            <h3 class="page-user-card__title">
              Мы хотим вывести идеи Open Source на качественно
            </h3>
            <p class="page-user-card__text">
              Мы хотим вывести идеи Open Source на качественно новый уровень, создав фонд и удобную онлайн платформу для
              работы над любыми открытыми проектами...
            </p>
            <a href="#" class="page-user-card__link">
              Смотреть проект
            </a>
          </div>
        </article>
        <!-- card -->
<!--        <article class="page-user-card">-->
<!--          <img src="{% static '/img/page-user/page-user-bg2.jpg' %}" alt="" class="page-user-card__img">-->
<!--          <div class="page-user-card__content-wrap">-->
<!--            <h3 class="page-user-card__title">-->
<!--              Мы хотим вывести идеи Open Source на качественно-->
<!--            </h3>-->
<!--            <p class="page-user-card__text">-->
<!--              Мы хотим вывести идеи Open Source на качественно новый уровень, создав фонд и удобную онлайн платформу для-->
<!--              работы над любыми открытыми проектами...-->
<!--            </p>-->
<!--            <a href="#" class="page-user-card__link">-->
<!--              Смотреть проект-->
<!--            </a>-->
<!--          </div>-->
<!--        </article>-->
<!--        &lt;!&ndash; card &ndash;&gt;-->
<!--        <article class="page-user-card">-->
<!--          <img src="{% static '/img/page-user/page-user-bg3.jpg' %}" alt="" class="page-user-card__img">-->
<!--          <div class="page-user-card__content-wrap">-->
<!--            <h3 class="page-user-card__title">-->
<!--              Мы хотим вывести идеи Open Source на качественно-->
<!--            </h3>-->
<!--            <p class="page-user-card__text">-->
<!--              Мы хотим вывести идеи Open Source на качественно новый уровень, создав фонд и удобную онлайн платформу для-->
<!--              работы над любыми открытыми проектами...-->
<!--            </p>-->
<!--            <a href="#" class="page-user-card__link">-->
<!--              Смотреть проект-->
<!--            </a>-->
<!--          </div>-->
<!--        </article>-->
<!--        &lt;!&ndash; card &ndash;&gt;-->
<!--        <article class="page-user-card">-->
<!--          <img src="../../img/page-user/page-user-bg4.jpg" alt="" class="page-user-card__img">-->
<!--          <div class="page-user-card__content-wrap">-->
<!--            <h3 class="page-user-card__title">-->
<!--              Мы хотим вывести идеи Open Source на качественно-->
<!--            </h3>-->
<!--            <p class="page-user-card__text">-->
<!--              Мы хотим вывести идеи Open Source на качественно новый уровень, создав фонд и удобную онлайн платформу для-->
<!--              работы над любыми открытыми проектами...-->
<!--            </p>-->
<!--            <a href="#" class="page-user-card__link">-->
<!--              Смотреть проект-->
<!--            </a>-->
<!--          </div>-->
<!--        </article>-->
<!--        &lt;!&ndash; card &ndash;&gt;-->
<!--        <article class="page-user-card">-->
<!--          <img src="../../img/page-user/page-user-bg5.jpg" alt="" class="page-user-card__img">-->
<!--          <div class="page-user-card__content-wrap">-->
<!--            <h3 class="page-user-card__title">-->
<!--              Мы хотим вывести идеи Open Source на качественно-->
<!--            </h3>-->
<!--            <p class="page-user-card__text">-->
<!--              Мы хотим вывести идеи Open Source на качественно новый уровень, создав фонд и удобную онлайн платформу для-->
<!--              работы над любыми открытыми проектами...-->
<!--            </p>-->
<!--            <a href="#" class="page-user-card__link">-->
<!--              Смотреть проект-->
<!--            </a>-->
<!--          </div>-->
<!--        </article>-->
<!--        &lt;!&ndash; card &ndash;&gt;-->
<!--        <article class="page-user-card">-->
<!--          <img src="../../img/page-user/page-user-bg6.jpg" alt="" class="page-user-card__img">-->
<!--          <div class="page-user-card__content-wrap">-->
<!--            <h3 class="page-user-card__title">-->
<!--              Мы хотим вывести идеи Open Source на качественно-->
<!--            </h3>-->
<!--            <p class="page-user-card__text">-->
<!--              Мы хотим вывести идеи Open Source на качественно новый уровень, создав фонд и удобную онлайн платформу для-->
<!--              работы над любыми открытыми проектами...-->
<!--            </p>-->
<!--            <a href="#" class="page-user-card__link">-->
<!--              Смотреть проект-->
<!--            </a>-->
<!--          </div>-->
<!--        </article>-->
      </div>
    </div>
  </div>
</div>

{% endif %}
NOT
{% endblock %}

accounts/templates/accounts/profileupdate.html
{% extends 'index.html' %}

{% load static %}
{% block page_title %}
{{ instance }}
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}


{% block content %}
{% if request.user.pk == user.pk or request.user.is_superuser %}
<div class="page-login page-auth">
    <div class="page-auth__content">
<form method="POST" enctype="multipart/form-data">
    <div class="form-horizontal">
        {% csrf_token %}

        {% for err in form.not_field_errors %}
        <div class="alert alert-danger" role="alert">
            <span>{{ err}}</span>
        </div>
        {% endfor %}

        {% for field in form %}
        <div class="fpage-auth__auth-form">
            <label class="input__label" for="{{ field.name }}">
                {{ field.label }}
            </label>

                {{ field }}

            {% for err in field.errors %}
            <small class="">{{ err }}</small>
            {% endfor %}

        </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button class="btn btn-danger" name="save" value="ok">Update</button>
            </div>
        </div>
    </div>
</form>
    </div>
</div>
{% endif %}
{% endblock %}

accounts/templates/accounts/resend_activation_code.html
{% extends 'index.html' %}

{% load static %}
{% load bootstrap4 %}

{% block page_title %}
Reset password
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% block page_login %}

<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Product</b>this admin</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Resend activation code</p>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form form_group_class='oneOptionFA' %}
<!--      <div class="form-group has-feedback">-->
<!--        <input type="email" class="form-control" placeholder="Email">-->
<!--        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>-->
<!--      </div>-->
<!--      <div class="form-group has-feedback">-->
<!--        <input type="password" class="form-control" placeholder="Password">-->
<!--        <span class="glyphicon glyphicon-lock form-control-feedback"></span>-->
<!--      </div>-->
      <div class="row">
        <div class="col-xs-8">
<!--          <div class="checkbox icheck">-->
<!--            <label>-->
<!--              <input type="checkbox"> Remember Me-->
<!--            </label>-->
<!--          </div>-->
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Send again</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

<!--    <div class="social-auth-links text-center">-->
<!--      <p>- OR -</p>-->
<!--      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using-->
<!--        Facebook</a>-->
<!--      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using-->
<!--        Google+</a>-->
<!--    </div>-->
    <!-- /.social-auth-links -->

    <a href="{% url 'accounts:login' %}" class="text-center">Login</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->


{% endblock %}

accounts/templates/accounts/restore_password_confirm.html
{% extends 'index.html' %}

{% load static %}

{% block page_title %}
Восстановление пароля
{% endblock %}

{% block page_styles %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

{% load bootstrap4 %}

{% block page_content %}
<div class="loginBack">
    <div class="centralBlock">
        <div class="contentCB">
    <h4>Восстановление пароля</h4>

    {% if validlink %}

      <form method="post" class="loginForms">

                {% csrf_token %}
                <div class="oneOptionFA ">
                    {% bootstrap_form form %}
                </div>
                <div class="oneOptionFA">
                    <input type="submit" value="Прислать" class="submAuth">

            </form>

            <div class="loginLinkRP">

    {% else %}

        <div class="loginLinkAlert">
            Данная ссылка недействительна. <br />
            Либо срок действия ее прошел либо уже ей воспользовались. <br />
            Запросите еще раз.
        </div>

    {% endif %}
        </div>
    </div>
</div>
{% endblock %}