accounts/urls.py
from django.urls import path
from .views.profile_views import MyProfile, MyProfileUpdate
from .views.users_views import UsersList
from .views.sign_views import (
    LogInView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView
)


app_name = 'accounts'


urlpatterns = [
    path('login/', LogInView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    #
    # path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),
    #
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),
    #
    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),
    #
    #
    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
    path('<int:pk>', MyProfile.as_view(), name='myprofile'),
    path('profileupdate/<int:pk>', MyProfileUpdate.as_view(), name='profileupdate'),
    # path('users/', AllUsersList.as_view(), name='users'),
    # path('create/', CreateUser.as_view(), name='create'),
    # path('delete/<int:pk>', DeleteUser.as_view(), name='delete'),
    # path('detail/<int:pk>', DetailUser.as_view(), name='detail'),
    # path('update/<int:pk>', UserUpdate.as_view(), name='update'),
    # path('mygrouplist/', MyGroupList.as_view(), name='mygrouplist'),
    path('users/', UsersList.as_view(), name='users'),
]

api/urls.py
from api.views.accounts import AccountViewSet
from api.views.invites import InviteViewSet, InviteRegistrationViewSet
from api.views.projects import ProjectViewSet
from api.views.donations import DonationViewSet

from rest_framework.routers import DefaultRouter
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views.accounts import account_registration_handler
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="API for project GrandCore",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register('user', AccountViewSet)
router.register('invite', InviteViewSet)
router.register('invite_reg', InviteRegistrationViewSet)
router.register('project', ProjectViewSet)
router.register('donation', DonationViewSet)

jwturlpatterns = [
    path('/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('register_user', account_registration_handler),
] + router.urls  + jwturlpatterns

backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import about_page, home_page
from accounts.views.users_views import UsersList

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("accounts/", include("accounts.urls")),
    path("about/", about_page, name="about"),
    path("", home_page, name="home"),
    path("projects/", include("projects.urls")),
    path("community/", UsersList.as_view(), name="community"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

backend/views.py
from django.template import loader
from django.http import HttpResponse
from projects.models import Project
from accounts.models import Account
from donations.models import Donation, NowMoneyAllTimeCounter, FoundMoneyAllTimeCounter, DeficitMoneyCounter
from django.db.models import Sum


def about_page(request):
    template = loader.get_template('about.html')
    context = {'text': 'HELLO'}
    return HttpResponse(template.render(context, request))


def home_page(request):
    template = loader.get_template('home.html')
    projects = Project.objects.filter().order_by('-created')[:6]
    accounts = Account.objects.filter(is_active=True, is_deleted=False,)[:6]
    donations = Donation.objects.filter().order_by('-created')[:6]

    # counters #
    platform_users = Account.objects.filter(is_active=True, is_deleted=False,).count()
    platform_projects = Project.objects.filter().order_by('-created').count()
    found_money_all_time = FoundMoneyAllTimeCounter.objects.filter().order_by('-created').last()
    now_money_all_time = NowMoneyAllTimeCounter.objects.filter().order_by('-created').last()
    deficit_money_сounter = DeficitMoneyCounter.objects.filter().order_by('-created').last()
    context = {
        'projects': projects,
        'accounts': accounts,
        'platform_users': platform_users,
        'platform_projects': platform_projects,
        'donations': donations,
        'found_money_all_time': found_money_all_time,
        'now_money_all_time': now_money_all_time,
        'deficit_money_сounter': deficit_money_сounter,
    }
    return HttpResponse(template.render(context, request))

backend/templates/includes/footer.html
{% load static %}

<footer class="footer">
    <a class="footer__logo" href="/"></a>
    <nav class="footer-nav">
        <span class="footer-nav__item footer-nav__copy">2019-2020 MIT</span>
        <a class="footer-nav__item item" href="/about">О фонде</a>
        <a class="footer-nav__item item" href="/projects">Проекты</a>
        <a class="footer-nav__item item" href="/community">Участники</a>
        <a class="footer-nav__item item" href="/angels">Спонсоры</a>
        <a class="footer-nav__item item" href="/politics">Политика конфиденциальности</a>
    </nav>
    <div class="footer-socials">
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/vk.svg' %}" alt="vk">
        </a>
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/youtube.svg' %}" alt="youtube">
        </a>
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/telegram.svg' %}" alt="telegram">
        </a>
        <a class="footer-socials__item" href="#">
            <img src="{% static '/img/social-icons/email.svg' %}" alt="email">
        </a>
    </div>
</footer>

backend/templates/includes/header.html
    <header class="header">
      <div class="header-left-burger" id="burger-btn">
        <label class="burger-toggle"
          ><input type="checkbox" />
          <div>
            <div><span></span> <span></span></div>
            <svg><use xlink:href="#path"></use></svg> <svg><use xlink:href="#path"></use></svg></div
        ></label>
        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
          <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 44" id="path">
            <path d="M22,22 L2,22 C2,11 11,2 22,2 C33,2 42,11 42,22"></path>
          </symbol>
        </svg>
      </div>
      <div class="header-left">
        <a class="header-left__logo" href="/"></a>
        <nav class="header-left__nav nav">
          <a class="header-left__nav-item item" href="/projects">Софт</a>
          <a class="header-left__nav-item item" href="/projects">Игры</a>
          <a class="header-left__nav-item item" href="/projects">Сервисы</a>
          <a class="header-left__nav-item item" href="/projects">Изделия</a>
          <a class="header-left__nav-item item" href="/projects">Тексты</a>
        </nav>
      </div>
      <div class="header-right">
        <nav class="header-right__nav">
          <a class="header-right__nav-item item" href="/about">О фонде</a>
          <a class="header-right__nav-item item" href="/angels">Спонсоры</a>
          <a class="header-right__nav-item item" href="/community">Участники</a>
        </nav>

        <div class="header-right-btns">
            <div class="header-right-btns__search">
            <button
              class="header-right-btns__search-btn header-right-btns__search-btn--action btn btn-small"
              id="search-btn-action"
            ></button>
            <input
              type="search"
              class="header-right-btns__search-field search-field"
              id="search-field"
              placeholder="Поиск"
            />
            <button class="header-right-btns__close-btn btn btn-small" id="close-search-field"></button>
          </div>
          <button class="header-right-btns__more-btn btn btn--small" id="show-more"></button>
          <button class="header-right-btns__search-btn btn btn-small" id="search-btn"></button>
            {% if not user.is_authenticated %}

            {% else %}
          <img class="header-right-btns-avlogin" id="avlogin" src="/media/{% firstof user.avatar 'user-placeholder.svg' %}" />
            {% endif %}
        </div>
        {% if not user.is_authenticated %}
            <a href="{% url 'accounts:login' %}" class="header-mobile-nav__signup-btn btn btn--green">Войти</a>
        {% else %}
        <nav class="header-right__avlogin">
          <a class="header-right__avlogin-item item" href="{% url 'accounts:myprofile' pk=user.pk %}">Личный Кабинет</a>
          <a class="header-right__avlogin-item item" href="/admin/">Админ. Панель</a>
          <div class="header-right__avlogin-item-sep item"></div>
          <a class="header-right__avlogin-item item" href="{% url 'accounts:logout' %}">Выход</a>
        </nav>
          {% endif %}
      </div>
    </header>

backend/templates/includes/nav.html
    <div class="overlay overlay--hidden"></div>
    <div class="header-mobile-nav header-mobile-nav--hidden">
      <div class="header-mobile-nav__close">
        <button class="header-mobile-nav__close-btn btn btn-small" id="close-mobile-nav"></button>
      </div>
      <nav class="header-mobile-nav__nav">
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Софт</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Игры</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Cервисы</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Изделия</b></a>
        <a class="header-mobile-nav__nav-item item" href="/projects"><b>Тексты</b></a>
      </nav>
      <nav class="header-mobile-nav__nav">
        <a class="header-mobile-nav__nav-item item" href="/about">О фонде</a>
        <a class="header-mobile-nav__nav-item item" href="/angels">Спонсоры</a>
        <a class="header-mobile-nav__nav-item item" href="/community">Участники</a>
      </nav>
              {% if not user.is_authenticated %}
        <a href="{% url 'accounts:login' %}" class="header-mobile-nav__signup-btn btn btn--green">Войти</a>
        {% else %}
      <nav class="header-mobile-nav__nav">

        <img class="header-mobile-nav__avlogin" src="/media/{% firstof user.avatar 'user-placeholder.svg' %}" />
        <a class="header-mobile-nav__nav-item item" href="{% url 'accounts:myprofile' pk=user.pk %}">Личный Кабинет</a>
        <a class="header-mobile-nav__nav-item item" href="/admin/">Админ. Панель</a>
        <a href="{% url 'accounts:logout' %}" class="header-mobile-nav__signup-btn btn btn--green">Выйти</a>

      </nav>
              {% endif %}
    </div>