api/urls.py
from api.views.accounts import AccountViewSet
from api.views.invites import InviteViewSet, InviteRegistrationViewSet
from api.views.projects import ProjectViewSet
from api.views.donations import DonationViewSet

from rest_framework.routers import DefaultRouter
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views.accounts import account_registration_handler
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="API for project GrandCore",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register('user', AccountViewSet)
router.register('invite', InviteViewSet)
router.register('invite_reg', InviteRegistrationViewSet)
router.register('project', ProjectViewSet)
router.register('donation', DonationViewSet)

jwturlpatterns = [
    path('/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('register_user', account_registration_handler),
] + router.urls  + jwturlpatterns

backend/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import about_page, home_page
from accounts.views.users_views import UsersList

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("accounts/", include("accounts.urls")),
    path("about/", about_page, name="about"),
    path("", home_page, name="home"),
    path("projects/", include("projects.urls")),
    path("community/", UsersList.as_view(), name="community"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

projects/urls.py
from django.urls import path
from .views import (
	ProjectListView, 
	# projects_from_category,
	ProjectDetailView, 
	projects_for_category,
)

app_name = 'projects'

urlpatterns = [
    path('', ProjectListView.as_view(), name="projects_list"),
    path('<int:pk>/', ProjectDetailView.as_view(), name="project"),
    # path('<slug:category>/', projects_from_category, name="projects_category"),
    path('category_id=<int:category_id>/', projects_for_category, name="projects_for_category"),
]

projects/models.py
from django.db import models
from django.urls import reverse

from core.models import TimeStampedModel
from accounts.models import Account
from mptt.models import MPTTModel, TreeForeignKey
from crum import get_current_user
from django.utils.translation import ugettext_lazy as _


class ProjectCategory(MPTTModel):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name=_('название категории'))
    slug = models.SlugField()
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        verbose_name=_('родительская категория'))

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = _('категория')
        verbose_name_plural = _('категории проекта')

    def __str__(self):
        return self.name


class Project(TimeStampedModel):
    title = models.CharField(
        max_length=100,
        verbose_name=_('название проекта')
    )

    description_brief = models.CharField(
        max_length=256,
        blank=True,
        default='',
        verbose_name=_('краткое описание')
    )

    description_full = models.TextField(
        blank=True,
        default='',
        verbose_name=_('история проекта')
    )

    category = models.ForeignKey(
        ProjectCategory,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name=_('категория')
    )

    amount_needed = models.PositiveIntegerField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_('необходимая сумма')
    )

    amount_available = models.PositiveIntegerField(
        blank=True,
        null=True,
        default=None,
        verbose_name=_('сумма в наличии')
    )

    author = models.ForeignKey(
        Account,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        default=None,
        related_name="projects",
        verbose_name=_('автор проекта')
    )

    image = models.ImageField(
        upload_to='projects/uploads',
        blank=True,
        verbose_name=_('лого')
    )

    file = models.FileField(
        upload_to='projects/uploads',
        blank=True,
        verbose_name='документы'
    )

    curators = models.ManyToManyField(
        Account,
        blank=True,
        related_name='project_curators',
        verbose_name='кураторы проекта')

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('создано')
    )

    class Meta:
        verbose_name = _('проект')
        verbose_name_plural = _('проекты')

    def __str__(self):
        return self.title

    def absolute_url(self):
        return reverse("project", kwargs={"id": self.id})

    def save(self, *args, **kwargs):
        user = get_current_user()
        if user and not user.pk:
            user = None
        if not self.pk:
            self.author = user
        self.modified_by = user
        super(Project, self).save(*args, **kwargs)

api/views/projects.py
from django.contrib.auth.mixins import LoginRequiredMixin
from projects.models import Project
from api.serializers.projects import ProjectSerializer
from rest_framework.pagination import PageNumberPagination
from rest_framework.viewsets import ModelViewSet


class LargeResultsSetPagination(PageNumberPagination):
    page_size = 5


class ProjectViewSet(LoginRequiredMixin, ModelViewSet):
    serializer_class = ProjectSerializer
    queryset = Project.objects.all()
    pagination_class = LargeResultsSetPagination

projects/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from .models import Project, ProjectCategory
from django.template.response import TemplateResponse


class ProjectListView(ListView):
    model = Project
    template_name = 'projects/projects_list.html'
    context_object_name = 'projects'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if not query == None:
            projects = Project.objects.filter(
                Q(title__icontains=query) |
                Q(description_brief__icontains=query) |
                Q(category__name__icontains=query)
            ).order_by('-created')
        else:
            projects = Project.objects.order_by('-created')
        return projects

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = ProjectCategory.objects.all()
        return context


class ProjectCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Project
    # form_class = ProjectCreateForm
    template_name = "projects/create-project.html"
    success_url = "/projects"
    success_message = "project %(title)s was successfully created"


class ProjectEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Project
    # form_class = ProjectUpdateForm
    template_name = "projects/edit-project.html"
    success_url = "/projects"
    success_message = "project %(title)s was successfully updated"


class ProjectDetailView(LoginRequiredMixin, SuccessMessageMixin, DetailView):
    model = Project
    # form_class = ProjectUpdateForm
    template_name = "projects/detail-project.html"
    # success_url = "/projects"
    success_message = "project %(title)s was successfully updated"


class ProjectDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Project
    template_name = "projects/delete-project.html"
    success_url = "/projects"
    success_message = "project %(title)s was successfully deleted"


# def projects_from_category(request, category):
#     template = 'projects/projects_list.html'
#     all_categories = ProjectCategory.objects.all()
#     category_inst = ProjectCategory.objects.get(slug=category)
#     category_projects = Project.objects.filter(category=category_inst)

#     context = {
#         'category': category,
#         'all_categories': all_categories,
#         'projects': category_projects,
#     }
#     return TemplateResponse(request, template, context)


def projects_for_category(request, category_id):
    template = 'projects/projects_for_category.html'
    all_categories = ProjectCategory.objects.all()
    category_tree = ProjectCategory.objects.get(id=category_id).get_descendants(include_self=True)
    ids = [i.id for i in category_tree]
    category_projects = Project.objects.filter(category__id__in=ids)

    context = {
        'category_id': category_id,
        'all_categories': all_categories,
        'projects': category_projects,
    }
    return TemplateResponse(request, template, context)

projects/templates/projects/projects_for_category.html
{% extends 'index.html' %}
{% load static %}
{% load mptt_tags %}
{% load bootstrap4 %}

{% block title %} Проекты {% endblock title %}
{% block page_styles %}
<link rel="stylesheet" href="{% static '/css/projects.bundle.css' %}" />
{% endblock %}

{% block content %}

<div class="page-list">
  <div class="page-list-content">
    <section class="page-list-content-list-header img">
       <div class="page-list-content-list-header-row">
           <h1 class="page-list-content-list-header-row__h1">
              Софт
           </h1>
       </div>
        <div class="page-list-content-list-header-col">
          <div class="page-list-content-list-header-col-1">
            <h3 class="page-list-content-list-header-col-1__h3">
               Найдите единомышленников и работайте над любыми открытыми проектами вместе
            </h3>
         </div>
        </div>
    </section>
    <section class="page-list-content-wrapper">
      <div id="openFilter" class="page-list-content-wrapper-sidebar">
        <div class="page-list-content-wrapper-sidebar-menutitle">
          <h2 class="page-list-content-wrapper-sidebar-menutitle__h2">
            Отфильтровать результаты
          </h2>
        </div>
        <div onclick="showHide('openFilter')" class="page-list-content-wrapper-sidebar-close">
            <img src="{% static '/img/close.svg' %}" style="margin: 18px;">
        </div>
        <div class="page-list-content-wrapper-sidebar-filters">
          <ul>
            <li class="page-list-content-wrapper-sidebar-filters-section-title">Софт <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
            <li class="page-list-content-wrapper-sidebar-filters-section-title">Игры <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
              <ul>
                <li>Mobile</li>
                <li>Action RPG</li>
                <li>Role-playing</li>
                <li>MMO RPG</li>
                <li>Strategy</li>
                <li>Simulation</li>
              </ul>
            </li>
            <li class="page-list-content-wrapper-sidebar-filters-section-title">Онлайн-сервисы <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
              <ul>
                <li>Windows</li>
                <li>Hack</li>
                <li>Security</li>
                <li>Corporate</li>
                <li>Social</li>
                <li>Linux</li>
              </ul>
            </li>

            <li class="page-list-content-wrapper-sidebar-filters-section-title">Изделия <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static '/img/list-marker.svg' %}"> </li>

            <li class="page-list-content-wrapper-sidebar-filters-section-title">Тексты <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static '/img/list-marker.svg' %}"> </li>
          </ul>
        </div>

        <br><br>
        <div class="page-list-content-wrapper-sidebar-filters" >
          {% for cat,structure in all_categories|tree_info %}
          {% if structure.new_level %}<ul class="page-list-content-wrapper-sidebar-filters-section-title"><li>{% else %}</li><li>{% endif %}
              <a href="{% url 'projects:projects_for_category' cat.id %}">{{ cat.name }} </a> <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static '/img/list-marker.svg' %}">
            {% for level in structure.closed_levels %}</li></ul>
            {% endfor %}
          {% endfor %}
        </div> 
      </div>

        <div class="page-list-content-wrapper-conteiner">
          <div class="page-list-content-wrapper-conteiner-top">
            <div onclick="showHide('openFilter')" class="page-list-content-wrapper-conteiner-top-filtercontaiber-chosefilter">
              <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-chosefilter-field">
                <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-chosefilter-field-icon"></div>
              </div>
            </div>
            <div class="page-list-content-wrapper-conteiner-top-search">
              <div class="page-list-content-wrapper-conteiner-top-search-field">
                <div class="page-list-content-wrapper-conteiner-top-search-field-icon"></div>
                <form action="/projects" method="get">
                <input class="page-list-content-wrapper-conteiner-top-search-field-input" placeholder="Поиск" name="q" type="text"></input>
                </form>
              </div>
            </div>
            <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-makefilter">
              <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-makefilter-field">
                <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-makefilter-field-icon"></div>
              </div>
            </div>
          </div>
          <div class="page-list-content-wrapper-conteiner-grid">

            {% if projects %}
            {% for project in projects %}

            <div class="page-list-content-wrapper-conteiner-row-col">
              <div class="page-list-content-wrapper-conteiner-row-col-imgconteiner">
                <img class="page-list-content-wrapper-conteiner-row-col-imgconteiner-img" src="/media/{{ project.image }}">
              </div>
              <div class="page-list-content-wrapper-conteiner-row-col-inside" style="margin: 0;">
                <h4 class="page-list-content-wrapper-conteiner-row-col-inside__h4" style="margin: 0;">
                  {{ project.title }}
                </h4>
                <p class="page-list-content-wrapper-conteiner-row-col-inside-description" style="margin: 0;">
                  {{ project.description_brief }}
                </p>
              </div>
            </div>
            {% endfor %}
            {% endif %}
          </div>

          <div class="page-list-content-wrapper-conteiner-row-download">
            <a class="page-list-content-wrapper-conteiner-row-download-btn" href="#">Загрузи ещё</a>
          </div>
        </div>
    </section>
</div>
</div>

{% endblock content %}

{% block page_js %}

<script type="text/javascript">

    function showHide(id) {
        var el = document.getElementById(id);
            if( el && el.style.display == 'block')
                el.style.display = 'none';
            else
                el.style.display = 'block';
        }

    window.onresize = function(event) {
        var width = window.innerWidth;
        console.log(width);
        if (width > 1380) {
            var el = document.getElementById("openFilter");
            el.style.display = 'block';
        } else {
            var el = document.getElementById("openFilter");
            el.style.display = 'none';
        }
    };

    // $(window).resize(function() {
    //  var width = $(window).width();
    //  if (width > 1379) {
    //      var el = document.getElementById("openFilter");
    //      el.style.display = 'block';
    //  }
    // });

</script>

{% endblock page_js %}

projects/templates/projects/projects_list.html
{% extends 'index.html' %}
{% load static %}
{% load mptt_tags %}
{% load bootstrap4 %}

{% block title %} Проекты {% endblock title %}
{% block page_styles %}
<link rel="stylesheet" href="{% static '/css/projects.bundle.css' %}" />
{% endblock %}

{% block content %}

<div class="page-list">
  <div class="page-list-content">
    <section class="page-list-content-list-header img">
       <div class="page-list-content-list-header-row">
           <h1 class="page-list-content-list-header-row__h1">
              Софт
           </h1>
       </div>
        <div class="page-list-content-list-header-col">
          <div class="page-list-content-list-header-col-1">
            <h3 class="page-list-content-list-header-col-1__h3">
               Найдите единомышленников и работайте над любыми открытыми проектами вместе
            </h3>
         </div>
        </div>
    </section>
    <section class="page-list-content-wrapper">
      <div id="openFilter" class="page-list-content-wrapper-sidebar">
        <div class="page-list-content-wrapper-sidebar-menutitle">
          <h2 class="page-list-content-wrapper-sidebar-menutitle__h2">
            Отфильтровать результаты
          </h2>
        </div>
        <div onclick="showHide('openFilter')" class="page-list-content-wrapper-sidebar-close">
            <img src="{% static '/img/close.svg' %}" style="margin: 18px;">
        </div>
        <div class="page-list-content-wrapper-sidebar-filters">
          <ul>
            {% for cat in all_categories %}
              <li class="page-list-content-wrapper-sidebar-filters-section-title">{{cat.name}} <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
            {% endfor %}
            <li class="page-list-content-wrapper-sidebar-filters-section-title">Софт <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">

            <li class="page-list-content-wrapper-sidebar-filters-section-title">Игры <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
              <ul>
                <li>Mobile</li>
                <li>Action RPG</li>
                <li>Role-playing</li>
                <li>MMO RPG</li>
                <li>Strategy</li>
                <li>Simulation</li>
              </ul>
            </li>
            <li class="page-list-content-wrapper-sidebar-filters-section-title">Онлайн-сервисы <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
              <ul>
                <li>Windows</li>
                <li>Hack</li>
                <li>Security</li>
                <li>Corporate</li>
                <li>Social</li>
                <li>Linux</li>
              </ul>
            </li>

            <li class="page-list-content-wrapper-sidebar-filters-section-title">Изделия <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static '/img/list-marker.svg' %}"> </li>

            <li class="page-list-content-wrapper-sidebar-filters-section-title">Тексты <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static '/img/list-marker.svg' %}"> </li>
          </ul>
        </div>

        <br><br>
        <div class="page-list-content-wrapper-sidebar-filters" >
          {% for cat,structure in category|tree_info %}
          {% if structure.new_level %}<ul class="page-list-content-wrapper-sidebar-filters-section-title"><li>{% else %}</li><li>{% endif %}
              <a href="{% url 'projects:projects_for_category' cat.id %}">{{ cat.name }} </a> <img class="page-list-content-wrapper-sidebar-filters-section-title-icon" src="{% static 'img/list-marker.svg' %}">
            {% for level in structure.closed_levels %}</li><br></ul>
            {% endfor %}
          {% endfor %}
        </div> 
      </div>

        <div class="page-list-content-wrapper-conteiner">
          <div class="page-list-content-wrapper-conteiner-top">
            <div onclick="showHide('openFilter')" class="page-list-content-wrapper-conteiner-top-filtercontaiber-chosefilter">
              <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-chosefilter-field">
                <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-chosefilter-field-icon"></div>
              </div>
            </div>
            <div class=
            "page-list-content-wrapper-conteiner-top-search">
              <div class="page-list-content-wrapper-conteiner-top-search-field">
                <div class="page-list-content-wrapper-conteiner-top-search-field-icon"></div>
                <form action="/projects" method="get">
                <input class="page-list-content-wrapper-conteiner-top-search-field-input" placeholder="Поиск" name="q" type="text"></input>
                </form>
              </div>
            </div>
            <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-makefilter">
              <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-makefilter-field">
                <div class="page-list-content-wrapper-conteiner-top-filtercontaiber-makefilter-field-icon"></div>
              </div>
            </div>
          </div>
          <div class="page-list-content-wrapper-conteiner-grid">

            {% if projects %}
            {% for project in projects %}

            <div class="page-list-content-wrapper-conteiner-row-col">
              <div class="page-list-content-wrapper-conteiner-row-col-imgconteiner">
                <img class="page-list-content-wrapper-conteiner-row-col-imgconteiner-img" src="/media/{{ project.image }}">
              </div>
              <div class="page-list-content-wrapper-conteiner-row-col-inside" style="margin: 0;">
                <h4 class="page-list-content-wrapper-conteiner-row-col-inside__h4" style="margin: 0;">
                  {{ project.title }}
                </h4>
                <p class="page-list-content-wrapper-conteiner-row-col-inside-description" style="margin: 0;">
                  {{ project.description_brief }}
                </p>
              </div>
            </div>
            {% endfor %}
            {% endif %}
          </div>

          <div class="page-list-content-wrapper-conteiner-row-download">
            <a class="page-list-content-wrapper-conteiner-row-download-btn" href="#">Загрузи ещё</a>
          </div>
        </div>
    </section>
</div>
</div>

{% endblock content %}

{% block page_js %}

<script type="text/javascript">

    function showHide(id) {
        var el = document.getElementById(id);
            if( el && el.style.display == 'block')
                el.style.display = 'none';
            else
                el.style.display = 'block';
        }

    window.onresize = function(event) {
        var width = window.innerWidth;
        console.log(width);
        if (width > 1380) {
            var el = document.getElementById("openFilter");
            el.style.display = 'block';
        } else {
            var el = document.getElementById("openFilter");
            el.style.display = 'none';
        }
    };

    // $(window).resize(function() {
    //  var width = $(window).width();
    //  if (width > 1379) {
    //      var el = document.getElementById("openFilter");
    //      el.style.display = 'block';
    //  }
    // });

</script>

{% endblock page_js %}